symfony-formation7/src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column]
    private ?int $nbreHeures = null;

    #[ORM\Column(length: 255)]
    private ?string $departement = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\ManyToOne(targetEntity:Produit::class)]
    #[ORM\JoinColumn(nullable:true)] 
    private $Produit = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getNbreHeures(): ?int
    {
        return $this->nbreHeures;
    }

    public function setNbreHeures(int $nbreHeures): static
    {
        $this->nbreHeures = $nbreHeures;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): static
    {
        $this->departement = $departement;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->Produit;
    }

    public function setProduit(?Produit $Produit): static
    {
        $this->Produit = $Produit;

        return $this;
    }
}

symfony-formation7/src/Controller/RechercheController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Employe;
use App\Entity\User;
use App\Entity\Inscription;
use App\Entity\Produit;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\InscriptionRepository;
use App\Form\FormationType;
use App\Form\RechercherInscriptionType;
use App\Form\RechercheLettreType;




class RechercheController extends AbstractController
{
    #[Route('/rechInscription', name: 'app_rech')]
    public function rechercheInscriptions(Request $request, ManagerRegistry $doctrine)
    {
        $form = $this->createForm(RechercherInscriptionType::class);        
        $form->handleRequest($request);
        
        $message = '';
        $groupedInscriptions = [];
    
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $nom = $data->getNom();
            $prenom = $data->getPrenom();
    
            $inscriptions = $doctrine->getRepository(Inscription::class)->rechInscriptionsEmployeNomPrenom($nom, $prenom);
    
            foreach ($inscriptions as $inscription) {
                $employeId = $inscription->getLuser()->getId();
                if (!isset($groupedInscriptions[$employeId])) {
                    $groupedInscriptions[$employeId] = [
                        'user' => $inscription->getLuser(),
                        'formations' => []
                    ];
                }
                $groupedInscriptions[$employeId]['formations'][] = $inscription;
            }
    
            if (empty($groupedInscriptions)) {
                $message = "Non trouvé";
            } else {
                $message = "TROUVE";
            }
        }
    
        return $this->render('recherche/form.html.twig', [
            'form' => $form->createView(),
            'groupedInscriptions' => $groupedInscriptions,
            'message' => $message
        ]);
    }

    #[Route('/ChercherLettre', name:'app_chercher_lettre')]
    public function chercherLettre(Request $request, ManagerRegistry $doctrine)
    {
        $form = $this->createForm(RechercheLettreType::class);
        $form->handleRequest($request);
    
        $employes = [];
        $message = '';
    
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $lettre = $data->getLettre();
    
            if (strlen($lettre) === 1) {
                $entityManager = $doctrine->getManager();
                $employes = $entityManager->getRepository(User::class)->createQueryBuilder('e')
                    ->where('e.prenom LIKE :lettre')
                    ->setParameter('lettre', $lettre . '%')
                    ->getQuery()
                    ->getResult();
            } else {
                $message = 'Veuillez saisir une seule lettre.';
            }
        }
    
        return $this->render('formation/Lettre.html.twig', [
            'form' => $form->createView(),
            'employes' => $employes,
            'message' => $message,
        ]);

    }


    }

symfony-formation7/templates/recherche/form.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/login.css') }}?t={{ "now"|date("U") }}">
{% endblock %}

{% block title %}Recherche d'Inscriptions{% endblock %}

{% block body %}
    <h1>Recherche d'Inscriptions</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit">Rechercher</button>
    {{ form_end(form) }}

    {% if message %}
        <div class="alert alert-info">
            {{ message }}
        </div>
    {% endif %}

    {% if groupedInscriptions is not empty %}
        <table class="table">
            <thead>
                <tr>
                    <th>Nom de l'employé</th>
                    <th>Prénom de l'employé</th>
                    <th>Formations</th>
                    <th>date</th>
                </tr>
            </thead>
            <tbody>
                {% for employeData in groupedInscriptions %}
                    <tr>
                        <td>{{ employeData.user.nom }}</td>
                        <td>{{ employeData.user.prenom }}</td>
                        <td>
                            <ul>
                                {% for inscription in employeData.formations %}
                                    <li>
                                        {% if inscription.laFormation %}
                                            {% if inscription.laFormation.produit %}
                                                {{ inscription.laFormation.produit.libelle }}
                                                {{ inscription.laFormation.dateDebut|date("m/d/Y") }}
                                            {% else %}
                                                Aucun produit
                                            {% endif %}
                                        {% else %}
                                            Aucune formation
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucune inscription trouvée.</p>
    {% endif %}
{% endblock %}

symfony-formation7/templates/recherche/listeEmploye.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('styles/main.css') }}?t={{ "now"|date("U") }}">
{% endblock %}

{% block javascripts %}
    <script src= "/public/script.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
{% endblock %}

{% block title %}Liste des Employés{% endblock %}

{% block body %}
<div class="formation-list">
    <h2>Liste des Employés</h2>
    {% if message %}
        <p style="text-align: center;">{{ message }}</p>
    {% endif %}
    <div class="filter">
        <form method="get" action="{{ path('app_listeEmploye') }}">
            <input type="text" id="nom" name="nom" value="{{ currentNom }}" placeholder="Rechercher par Nom">
            <input type="text" id="prenom" name="prenom" value="{{ currentPrenom }}" placeholder="Rechercher par Prénom">
            <button type="submit">Rechercher</button>
        </form>
    </div>
    {% if ensEmployes is empty %}
        <p style="text-align: center;">Aucun employé trouvé</p>
    {% else %}
        <div class="table-container">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>E-mail</th>
                        <th>Statut</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in ensEmployes %}
                        <tr onclick="showAlert('{{ user.nom }}', '{{ user.prenom }}', '{{ user.roles|join(', ') }}')">
                            <td>{{ user.nom }}</td>
                            <td>{{ user.prenom }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.roles|join(', ') }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
</div>

<script>
    function showAlert(nom, prenom, statut) {
        alert("\nNom: " + nom + "\nPrénom: " + prenom + "\nStatut: " + statut);
    }
</script>
{% endblock %}

symfony-formation7/templates/recherche/rechercheOneBy.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultat de la recherche{% endblock %}

{% block body %}
    <h1>Résultat de la recherche</h1>

    {% if message is defined and message is not empty %}
        <div class="alert alert-success">{{ message }}</div>
    {% endif %}

    {% for message in app.flashes('warning') %}
        <div class="alert alert-warning">{{ message }}</div>
    {% endfor %}

    {% if ensRecherche is not empty %}
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Statut</th>
            </tr>
        </thead>
        <tbody>
            <tbody>
                <tr>
                    <td>{{ ensRecherche.nom }}</td>
                    <td>{{ ensRecherche.statut }}</td>
                </tr>
            </tbody>
            {% for employe in ensRecherche %}
                <tr>
                    <td>{{ employe.nom }}</td>
                    <td>{{ employe.statut }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>Aucun employé trouvé.</p>
    {% endif %}

{% endblock %}